package main

type CreditCards struct {
	FeaturedCards []struct {
		ApprovalRate string `json:"approvalRate"`
		Name string `json:"name"`
		Description string `json:"description"`
		Image string `json:"image"`
		LinkGeneralDesktop string `json:"linkGeneralDesktop"`
		LinkGeneralMobile string `json:"linkGeneralMobile"`
		LinkFunnelDesktop interface{} `json:"linkFunnelDesktop"`
		LinkFunnelMobile interface{} `json:"linkFunnelMobile"`
		CggID string `json:"cggId"`
		HasApplyButton bool `json:"hasApplyButton"`
		HasApplicationForm bool `json:"hasApplicationForm"`
		ShowCTALeadCapture bool `json:"showCTALeadCapture"`
		BestDealsColumnReference string `json:"bestDealsColumnReference"`
		BestCardDesc string `json:"bestCardDesc"`
		NewJoinerDesc interface{} `json:"newJoinerDesc"`
		IsNewJoiner bool `json:"isNewJoiner"`
		Provider struct {
			CggID string `json:"cggId"`
			Name string `json:"name"`
			Image string `json:"image"`
			Link string `json:"link"`
			LinkMobile interface{} `json:"linkMobile"`
			Description interface{} `json:"description"`
			ProviderDisclaimer string `json:"providerDisclaimer"`
			About string `json:"about"`
			AboutShortDesc string `json:"aboutShortDesc"`
			Terms interface{} `json:"terms"`
			Address interface{} `json:"address"`
			ProductDescription string `json:"productDescription"`
		} `json:"provider"`
		Feature []string `json:"feature"`
		AdditionalFeature []interface{} `json:"additionalFeature"`
		Specification []string `json:"specification"`
		Footnote []string `json:"footnote"`
		Banner struct {
			BannerDesc string `json:"bannerDesc"`
			AffiliateBannerDesc interface{} `json:"affiliateBannerDesc"`
			BannerType string `json:"bannerType"`
			BannerExpiryDate interface{} `json:"bannerExpiryDate"`
		} `json:"banner"`
		Offers []struct {
			Title interface{} `json:"title"`
			Descriptions []string `json:"descriptions"`
			Conditions []string `json:"conditions"`
			ExpiryDate interface{} `json:"expiryDate"`
			OfferType string `json:"offerType"`
		} `json:"offers"`
		Fee struct {
			AnnualFee float64 `json:"annualFee"`
			AnnualFeeLabel interface{} `json:"annualFeeLabel"`
			AnnualFeeDesc interface{} `json:"annualFeeDesc"`
			ForeignCurrencyTransactionFee float64 `json:"foreignCurrencyTransactionFee"`
			InterestFreeDay int `json:"interestFreeDay"`
			InterestFreeWeek interface{} `json:"interestFreeWeek"`
			InterestFreeMonth interface{} `json:"interestFreeMonth"`
			InterestFreePeriodDesc interface{} `json:"interestFreePeriodDesc"`
			InterestRate float64 `json:"interestRate"`
			InterestRateDesc interface{} `json:"interestRateDesc"`
			InterestRateLabel interface{} `json:"interestRateLabel"`
			AnnualFeeWaiverDesc string `json:"annualFeeWaiverDesc"`
			AnnualFeeSuppCardDesc interface{} `json:"annualFeeSuppCardDesc"`
			RetailPurchaseDelinquencyAPR float64 `json:"retailPurchaseDelinquencyAPR"`
			CashAdvanceDelinquencyAPR float64 `json:"cashAdvanceDelinquencyAPR"`
			MinRepay interface{} `json:"minRepay"`
			MinRepayDesc string `json:"minRepayDesc"`
			LatePayCharge interface{} `json:"latePayCharge"`
			LatePayChargeDesc string `json:"latePayChargeDesc"`
			BasicAPR float64 `json:"basicAPR"`
			BasicAPRDesc interface{} `json:"basicAPRDesc"`
			BasicAPRLabel interface{} `json:"basicAPRLabel"`
			CardLimit float64 `json:"cardLimit"`
			CardLimitDesc interface{} `json:"cardLimitDesc"`
			CardLimitLabel interface{} `json:"cardLimitLabel"`
			ActivationFee interface{} `json:"activationFee"`
			ActivationFeeDesc interface{} `json:"activationFeeDesc"`
			ActivationFeeLabel interface{} `json:"activationFeeLabel"`
			ChargingFee interface{} `json:"chargingFee"`
			ChargingFeeDesc interface{} `json:"chargingFeeDesc"`
			FreePaymentEU interface{} `json:"freePaymentEU"`
			ForeignFee float64 `json:"foreignFee"`
			ForeignFeeDesc interface{} `json:"foreignFeeDesc"`
			CashWithdrawalFeeEUDesc interface{} `json:"cashWithdrawalFeeEUDesc"`
			CashWithdrawalFeeOutsideEUDesc interface{} `json:"cashWithdrawalFeeOutsideEUDesc"`
		} `json:"fee"`
		Eligibility struct {
			MinAnnualIncome float64 `json:"minAnnualIncome"`
			MinAnnualIncomeForeigner float64 `json:"minAnnualIncomeForeigner"`
			MinMonthlyIncomeForeigner interface{} `json:"minMonthlyIncomeForeigner"`
			MinNetIncome float64 `json:"minNetIncome"`
			MinAnnualIncomeDesc interface{} `json:"minAnnualIncomeDesc"`
			MinAnnualIncomeLabel interface{} `json:"minAnnualIncomeLabel"`
			Age int `json:"age"`
			MaxAge int `json:"maxAge"`
			AgeSuppCard interface{} `json:"ageSuppCard"`
			MinMonthlyIncome float64 `json:"minMonthlyIncome"`
			MaritialStatus []interface{} `json:"maritialStatus"`
			EmploymentStatus []interface{} `json:"employmentStatus"`
		} `json:"eligibility"`
		RewardTravel struct {
			Basic float64 `json:"basic"`
			Local float64 `json:"local"`
			Overseas float64 `json:"overseas"`
			Dining float64 `json:"dining"`
			OnlineShopping float64 `json:"onlineShopping"`
			ConversionFee float64 `json:"conversionFee"`
			Shopping float64 `json:"shopping"`
			AirmilesConversionFee float64 `json:"airmilesConversionFee"`
			PersonalAssistanceCoveredAmount float64 `json:"personalAssistanceCoveredAmount"`
			PersonalAssistanceCoveredDesc interface{} `json:"personalAssistanceCoveredDesc"`
			PersonalAssistanceCoveredLabel interface{} `json:"personalAssistanceCoveredLabel"`
			PersonalAssistanceCoveredInfo interface{} `json:"personalAssistanceCoveredInfo"`
			PersonalAssistanceCoveredInfoDesc interface{} `json:"personalAssistanceCoveredInfoDesc"`
			TravelCancellationCoveredAmount float64 `json:"travelCancellationCoveredAmount"`
			TravelCancellationCoveredDesc interface{} `json:"travelCancellationCoveredDesc"`
			TravelCancellationCoveredLabel interface{} `json:"travelCancellationCoveredLabel"`
			TravelCancellationCoveredInfo interface{} `json:"travelCancellationCoveredInfo"`
			TravelCancellationCoveredInfoDesc interface{} `json:"travelCancellationCoveredInfoDesc"`
			BasicDesc string `json:"basicDesc"`
			LocalDesc string `json:"localDesc"`
			BasicLabel string `json:"basicLabel"`
			LocalLabel string `json:"localLabel"`
			OverseasDesc string `json:"overseasDesc"`
			OverseasLabel string `json:"overseasLabel"`
			ConversionFeeDesc string `json:"conversionFeeDesc"`
			ConversionFeeLabel interface{} `json:"conversionFeeLabel"`
			DiningDesc string `json:"diningDesc"`
			DiningLabel string `json:"diningLabel"`
			OnlineShoppingDesc interface{} `json:"onlineShoppingDesc"`
			OnlineShoppingLabel interface{} `json:"onlineShoppingLabel"`
		} `json:"rewardTravel"`
		RewardCash struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
			Local float64 `json:"local"`
			LocalLabel interface{} `json:"localLabel"`
			LocalDesc interface{} `json:"localDesc"`
			Overseas float64 `json:"overseas"`
			OverseasLabel interface{} `json:"overseasLabel"`
			OverseasDesc interface{} `json:"overseasDesc"`
			Dining float64 `json:"dining"`
			DiningLabel interface{} `json:"diningLabel"`
			DiningDesc interface{} `json:"diningDesc"`
			OnlineShopping float64 `json:"onlineShopping"`
			OnlineShoppingLabel interface{} `json:"onlineShoppingLabel"`
			OnlineShoppingDesc interface{} `json:"onlineShoppingDesc"`
			ShoppingDesc interface{} `json:"shoppingDesc"`
			ShoppingLabel interface{} `json:"shoppingLabel"`
			Shopping float64 `json:"shopping"`
			Average interface{} `json:"average"`
			Max interface{} `json:"max"`
		} `json:"rewardCash"`
		RewardPoint struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
			Local float64 `json:"local"`
			Oversea float64 `json:"oversea"`
			Dining float64 `json:"dining"`
			OnlineShopping float64 `json:"onlineShopping"`
			AutoPayment float64 `json:"autoPayment"`
			Max interface{} `json:"max"`
			PointExpiryDate interface{} `json:"pointExpiryDate"`
		} `json:"rewardPoint"`
		RewardGas struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardGas"`
		RewardMovie struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardMovie"`
		RewardDiscount struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardDiscount"`
		RewardGeneral struct {
		} `json:"rewardGeneral"`
		Transfer struct {
			BalanceTransferRate float64 `json:"balanceTransferRate"`
			BalanceTransferRateDesc interface{} `json:"balanceTransferRateDesc"`
			BalanceTransferRateLabel interface{} `json:"balanceTransferRateLabel"`
			MinimumTransferAmount float64 `json:"minimumTransferAmount"`
			MinimumTransferAmountDesc interface{} `json:"minimumTransferAmountDesc"`
			MinimumTransferAmountLabel interface{} `json:"minimumTransferAmountLabel"`
		} `json:"transfer"`
		Others struct {
			WidgetHasOfferID int `json:"widgetHasOfferId"`
			WidgetHasOfferLinkID interface{} `json:"widgetHasOfferLinkId"`
			DoubleClickDesktopAdID int `json:"doubleClickDesktopAdId"`
			DoubleClickMobileAdID int `json:"doubleClickMobileAdId"`
		} `json:"others"`
	} `json:"featuredCards"`
	Cards []struct {
		ApprovalRate string `json:"approvalRate"`
		Name string `json:"name"`
		Description string `json:"description"`
		Image string `json:"image"`
		LinkGeneralDesktop string `json:"linkGeneralDesktop"`
		LinkGeneralMobile string `json:"linkGeneralMobile"`
		LinkFunnelDesktop interface{} `json:"linkFunnelDesktop"`
		LinkFunnelMobile interface{} `json:"linkFunnelMobile"`
		CggID string `json:"cggId"`
		HasApplyButton bool `json:"hasApplyButton"`
		HasApplicationForm bool `json:"hasApplicationForm"`
		ShowCTALeadCapture bool `json:"showCTALeadCapture"`
		BestDealsColumnReference string `json:"bestDealsColumnReference"`
		BestCardDesc string `json:"bestCardDesc"`
		NewJoinerDesc interface{} `json:"newJoinerDesc"`
		IsNewJoiner bool `json:"isNewJoiner"`
		Provider struct {
			CggID string `json:"cggId"`
			Name string `json:"name"`
			Image string `json:"image"`
			Link string `json:"link"`
			LinkMobile interface{} `json:"linkMobile"`
			Description interface{} `json:"description"`
			ProviderDisclaimer string `json:"providerDisclaimer"`
			About string `json:"about"`
			AboutShortDesc string `json:"aboutShortDesc"`
			Terms interface{} `json:"terms"`
			Address interface{} `json:"address"`
			ProductDescription string `json:"productDescription"`
		} `json:"provider"`
		Feature []string `json:"feature"`
		AdditionalFeature []interface{} `json:"additionalFeature"`
		Specification []string `json:"specification"`
		Footnote []string `json:"footnote"`
		Banner struct {
			BannerDesc interface{} `json:"bannerDesc"`
			AffiliateBannerDesc interface{} `json:"affiliateBannerDesc"`
			BannerType interface{} `json:"bannerType"`
			BannerExpiryDate interface{} `json:"bannerExpiryDate"`
		} `json:"banner"`
		Offers []struct {
			Title interface{} `json:"title"`
			Descriptions []string `json:"descriptions"`
			Conditions []string `json:"conditions"`
			ExpiryDate interface{} `json:"expiryDate"`
			OfferType string `json:"offerType"`
		} `json:"offers"`
		Fee struct {
			AnnualFee float64 `json:"annualFee"`
			AnnualFeeLabel interface{} `json:"annualFeeLabel"`
			AnnualFeeDesc interface{} `json:"annualFeeDesc"`
			ForeignCurrencyTransactionFee float64 `json:"foreignCurrencyTransactionFee"`
			InterestFreeDay int `json:"interestFreeDay"`
			InterestFreeWeek interface{} `json:"interestFreeWeek"`
			InterestFreeMonth interface{} `json:"interestFreeMonth"`
			InterestFreePeriodDesc interface{} `json:"interestFreePeriodDesc"`
			InterestRate float64 `json:"interestRate"`
			InterestRateDesc interface{} `json:"interestRateDesc"`
			InterestRateLabel interface{} `json:"interestRateLabel"`
			AnnualFeeWaiverDesc string `json:"annualFeeWaiverDesc"`
			AnnualFeeSuppCardDesc interface{} `json:"annualFeeSuppCardDesc"`
			RetailPurchaseDelinquencyAPR float64 `json:"retailPurchaseDelinquencyAPR"`
			CashAdvanceDelinquencyAPR float64 `json:"cashAdvanceDelinquencyAPR"`
			MinRepay interface{} `json:"minRepay"`
			MinRepayDesc string `json:"minRepayDesc"`
			LatePayCharge interface{} `json:"latePayCharge"`
			LatePayChargeDesc string `json:"latePayChargeDesc"`
			BasicAPR float64 `json:"basicAPR"`
			BasicAPRDesc interface{} `json:"basicAPRDesc"`
			BasicAPRLabel interface{} `json:"basicAPRLabel"`
			CardLimit float64 `json:"cardLimit"`
			CardLimitDesc interface{} `json:"cardLimitDesc"`
			CardLimitLabel interface{} `json:"cardLimitLabel"`
			ActivationFee interface{} `json:"activationFee"`
			ActivationFeeDesc interface{} `json:"activationFeeDesc"`
			ActivationFeeLabel interface{} `json:"activationFeeLabel"`
			ChargingFee interface{} `json:"chargingFee"`
			ChargingFeeDesc interface{} `json:"chargingFeeDesc"`
			FreePaymentEU interface{} `json:"freePaymentEU"`
			ForeignFee float64 `json:"foreignFee"`
			ForeignFeeDesc interface{} `json:"foreignFeeDesc"`
			CashWithdrawalFeeEUDesc interface{} `json:"cashWithdrawalFeeEUDesc"`
			CashWithdrawalFeeOutsideEUDesc interface{} `json:"cashWithdrawalFeeOutsideEUDesc"`
		} `json:"fee"`
		Eligibility struct {
			MinAnnualIncome float64 `json:"minAnnualIncome"`
			MinAnnualIncomeForeigner float64 `json:"minAnnualIncomeForeigner"`
			MinMonthlyIncomeForeigner interface{} `json:"minMonthlyIncomeForeigner"`
			MinNetIncome float64 `json:"minNetIncome"`
			MinAnnualIncomeDesc interface{} `json:"minAnnualIncomeDesc"`
			MinAnnualIncomeLabel interface{} `json:"minAnnualIncomeLabel"`
			Age int `json:"age"`
			MaxAge int `json:"maxAge"`
			AgeSuppCard interface{} `json:"ageSuppCard"`
			MinMonthlyIncome float64 `json:"minMonthlyIncome"`
			MaritialStatus []interface{} `json:"maritialStatus"`
			EmploymentStatus []interface{} `json:"employmentStatus"`
		} `json:"eligibility"`
		RewardTravel struct {
			Basic float64 `json:"basic"`
			Local float64 `json:"local"`
			Overseas float64 `json:"overseas"`
			Dining float64 `json:"dining"`
			OnlineShopping float64 `json:"onlineShopping"`
			ConversionFee float64 `json:"conversionFee"`
			Shopping float64 `json:"shopping"`
			AirmilesConversionFee float64 `json:"airmilesConversionFee"`
			PersonalAssistanceCoveredAmount float64 `json:"personalAssistanceCoveredAmount"`
			PersonalAssistanceCoveredDesc interface{} `json:"personalAssistanceCoveredDesc"`
			PersonalAssistanceCoveredLabel interface{} `json:"personalAssistanceCoveredLabel"`
			PersonalAssistanceCoveredInfo interface{} `json:"personalAssistanceCoveredInfo"`
			PersonalAssistanceCoveredInfoDesc interface{} `json:"personalAssistanceCoveredInfoDesc"`
			TravelCancellationCoveredAmount float64 `json:"travelCancellationCoveredAmount"`
			TravelCancellationCoveredDesc interface{} `json:"travelCancellationCoveredDesc"`
			TravelCancellationCoveredLabel interface{} `json:"travelCancellationCoveredLabel"`
			TravelCancellationCoveredInfo interface{} `json:"travelCancellationCoveredInfo"`
			TravelCancellationCoveredInfoDesc interface{} `json:"travelCancellationCoveredInfoDesc"`
			BasicDesc string `json:"basicDesc"`
			LocalDesc string `json:"localDesc"`
			BasicLabel string `json:"basicLabel"`
			LocalLabel string `json:"localLabel"`
			OverseasDesc string `json:"overseasDesc"`
			OverseasLabel string `json:"overseasLabel"`
			ConversionFeeDesc string `json:"conversionFeeDesc"`
			ConversionFeeLabel interface{} `json:"conversionFeeLabel"`
			DiningDesc interface{} `json:"diningDesc"`
			DiningLabel interface{} `json:"diningLabel"`
			OnlineShoppingDesc interface{} `json:"onlineShoppingDesc"`
			OnlineShoppingLabel interface{} `json:"onlineShoppingLabel"`
		} `json:"rewardTravel"`
		RewardCash struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
			Local float64 `json:"local"`
			LocalLabel interface{} `json:"localLabel"`
			LocalDesc interface{} `json:"localDesc"`
			Overseas float64 `json:"overseas"`
			OverseasLabel interface{} `json:"overseasLabel"`
			OverseasDesc interface{} `json:"overseasDesc"`
			Dining float64 `json:"dining"`
			DiningLabel interface{} `json:"diningLabel"`
			DiningDesc interface{} `json:"diningDesc"`
			OnlineShopping float64 `json:"onlineShopping"`
			OnlineShoppingLabel interface{} `json:"onlineShoppingLabel"`
			OnlineShoppingDesc interface{} `json:"onlineShoppingDesc"`
			ShoppingDesc interface{} `json:"shoppingDesc"`
			ShoppingLabel interface{} `json:"shoppingLabel"`
			Shopping float64 `json:"shopping"`
			Average interface{} `json:"average"`
			Max interface{} `json:"max"`
		} `json:"rewardCash"`
		RewardPoint struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
			Local float64 `json:"local"`
			Oversea float64 `json:"oversea"`
			Dining float64 `json:"dining"`
			OnlineShopping float64 `json:"onlineShopping"`
			AutoPayment float64 `json:"autoPayment"`
			Max interface{} `json:"max"`
			PointExpiryDate interface{} `json:"pointExpiryDate"`
		} `json:"rewardPoint"`
		RewardGas struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardGas"`
		RewardMovie struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardMovie"`
		RewardDiscount struct {
			Basic float64 `json:"basic"`
			BasicLabel interface{} `json:"basicLabel"`
			BasicDesc interface{} `json:"basicDesc"`
		} `json:"rewardDiscount"`
		RewardGeneral struct {
		} `json:"rewardGeneral"`
		Transfer struct {
			BalanceTransferRate float64 `json:"balanceTransferRate"`
			BalanceTransferRateDesc interface{} `json:"balanceTransferRateDesc"`
			BalanceTransferRateLabel interface{} `json:"balanceTransferRateLabel"`
			MinimumTransferAmount float64 `json:"minimumTransferAmount"`
			MinimumTransferAmountDesc interface{} `json:"minimumTransferAmountDesc"`
			MinimumTransferAmountLabel interface{} `json:"minimumTransferAmountLabel"`
		} `json:"transfer"`
		Others struct {
			WidgetHasOfferID int `json:"widgetHasOfferId"`
			WidgetHasOfferLinkID interface{} `json:"widgetHasOfferLinkId"`
			DoubleClickDesktopAdID int `json:"doubleClickDesktopAdId"`
			DoubleClickMobileAdID int `json:"doubleClickMobileAdId"`
		} `json:"others"`
	} `json:"cards"`
	Timestamp int `json:"timestamp"`
	TotalFeaturedCards int `json:"totalFeaturedCards"`
	TotalnonFeaturedCards int `json:"totalnonFeaturedCards"`
	TotalRecords int `json:"totalRecords"`
}
